AWSTemplateFormatVersion: "2010-09-09"

Description: Write parameters to parameter store

Parameters:
  GitHubUser:
    Description: Enter GitHub username of the repository owner
    Type: String
  GitHubOAuthToken:
    Description: Create a token with 'repo' and 'admin:repo_hook' permissions here https://github.com/settings/tokens
    Type: String
    NoEcho: 'true'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "GitHub credentials"
        Parameters:
          - GitHubUser
          - GitHubOAuthToken

Resources:
  GitHubUserName:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: GITHUBUSER
      Type: String 
      Value: !Ref GitHubUser
      Description: GitHub User
      AllowedPattern: "^[0-9a-zA-Z]{1,30}$"

  GitHubToken:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: GITHUBTOKEN
      Type: String 
      Value: !Ref GitHubOAuthToken
      Description: GitHub Token
      AllowedPattern: "^[0-9a-zA-Z]{1,30}$"

Outputs:
  GitHubUser:
    Description: GitHub user
    Value: !Ref GitHubUser
    Export:
      Name: !Sub "${AWS::StackName}-GitHubUser"    
  GitHubOAuthToken:
    Description: GitHub Token
    Value: !Ref GitHubOAuthToken
    Export:
      Name: !Sub "${AWS::StackName}-GitHubToken"         